import sys
import time
#import colorama
from colorama import Fore
print(Fore.MAGENTA + "Loading...")
time.sleep(3)
print(Fore.BLUE + "Welcome to Mad Lib\nPlease answer the following questions")
time.sleep(0.75)
print(Fore.MAGENTA + "Updating Questions...")
time.sleep(3)
print(Fore.LIGHTYELLOW_EX + "Let's Start!")

print(Fore.LIGHTGREEN_EX + " ")
NUM=int(input("Choose: 1, 2, 3: "))
if NUM < 1 or NUM > 3:
  print(Fore.RED + "Invalid Input. Please try again" + Fore.LIGHTGREEN_EX)
  NUM=int(input("Choose; 1, 2, 3: "))
if NUM == 1:
  S11=input("Person: ")
  P11=input("Place: ")
  M11=input("Vehicle: ")
  G11=input("Game: ")
  S21=input("Person: ")
  VPT11=input("Verb (past tense): ")
  S31=input("Person: ")
  CQ11=input("Was that his or her: ")
  D11=input("Device: ")
  time.sleep(0.75)
  print(Fore.MAGENTA + "Finding Sentence...")
  time.sleep(3)
  print(Fore.LIGHTCYAN_EX + "Yesterday, Me and " + str(S11) + " met in " + str(P11) + ". We came in a " + str(M11) + ". We played " + str(G11) + ". Then " + str(S21) + " arrived, and we all " + str(VPT11) + " to " + str(S31) + "'s house to see " + str(CQ11) + " new " + str(D11) + ". It was good!")
  print(Fore.LIGHTWHITE_EX + "Thanks for playing!")
  sys.exit()
if NUM == 2:
  print(Fore.LIGHTGREEN_EX + "")
  S12=input("Person: ")
  CQ12=input("Was that him or her: ")
  S22=input("Person: ")
  G12=input("Game: ")
  S32=input("Person: ")
  CQ22=input("Was that his or her: ")
  M12=input("Vehicle: ")
  D12=input("Device: ")
  VPT12=input("Verb(past tense): ")
  time.sleep(0.75)
  print(Fore.MAGENTA + "Finding Sentence...")
  time.sleep(3)
  print(Fore.LIGHTCYAN_EX + "Today, " + str(S12) + " came to my house. " + str(S22) + " also came with " + str(CQ12) + ". We played " + str(G12) + ". Then " + str(S32) + " arrived in " + str(CQ22) + " " + str(M12) + " with " + str(CQ22) + " " + str(D12) + ". We " + str(VPT12) + " and talked. We had fun!")
if NUM == 3:
  N13=int(input("Number: "))
  N2D13=int(input("Number(2 Digit): "))
  P13=input("Place: ")
  SG13=input("Sport: ")   
  S13=input("Person: ")
  S23=input("Person: ")
  S33=input("Person: ")
  T13=input("Toy: ")
  T23=input("Toy: ")
  time.sleep(0.75)
  print(Fore.MAGENTA + "Finding Sentence...")
  time.sleep(3)
  print(Fore.LIGHTCYAN_EX + "Today, I won $" + str(N13) + "." + str(N2D13) + " in " + str(P13) + " by winning 1st place in " + str(SG13) + ". I shared the money with " + str(S13) + ", " + str(S23) + " and " + str(S33) + ". We all bought a " + str(T13) + " except for " + str(S33) + " who got a " + str(T23) + ". We all liked our toys!")  